    LD      IX, (tempSwapArea)
    LD      DE, XMAX
    LD      A, $80
    ADD     IX, DE
    LD      (IX+2), A
    LD      (IX+8), A
    ADD     IX, DE
    LD      (IX+3), A
    LD      (IX+9), A
    ADD     IX, DE
    LD      (IX+1), A
    LD      (IX+2), A
    LD      (IX+3), A
    LD      (IX+7), A
    LD      (IX+8), A
    LD      (IX+9), A
